name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: make
      run: cmake --build build --parallel

    - name: ctest
      working-directory: build
      run: ctest --output-on-failure

    - name: run
      run: ./build/pro1
